# Generated by Django 5.2.17 on 2026-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_file',
            field=models.FileField(blank=True, help_text='Shartnoma fayli (Word/PDF)', null=True, upload_to='contracts/'),
        ),
    ]
