# Generated by Django 5.2.17 on 2026-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Sotuv paytidagi tannarx (snapshot) — keyin mahsulot narxi o'zgarsa ham tarixiy profit o'zgarmaydi", max_digits=14, null=True),
        ),
    ]
