# Generated by Django 5.2.17 on 2026-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Jismoniy shaxs'), ('legal', 'Yuridik shaxs')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.TextField(blank=True, help_text='Shifrlangan (Fernet)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.TextField(blank=True, help_text='Shifrlangan (Fernet)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.TextField(blank=True, help_text='Shifrlangan (Fernet)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.TextField(blank=True, help_text='Shifrlangan (Fernet)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pinfl',
            field=models.TextField(blank=True, help_text='Shifrlangan (Fernet)', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.TextField(help_text='Shifrlangan (Fernet)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.TextField(blank=True, help_text='Shifrlangan (Fernet)', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.TextField(blank=True, help_text='Shifrlangan (Fernet)', null=True),
        ),
    ]
