# Generated by Django 5.2.15 on 2026-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=200, verbose_name='Bot Token')),
                ('chat_id', models.CharField(max_length=50, verbose_name='Guruh Chat ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Telegram Sozlama',
                'verbose_name_plural': 'Telegram Sozlamalar',
            },
        ),
    ]
